-- Reseta os dados de aplicacao preservando apenas autenticacao e perfis de usuario.
-- Mantem `auth.users` e `public.user_profiles`.

TRUNCATE TABLE
  public.alert_notifications,
  public.alert_rules,
  public.operational_supervision,
  public.well_checklists,
  public.project_team_roles,
  public.team_members,
  public.project_members,
  public.audit_logs,
  public.well_bsw_manual_entries,
  public.srt_well_tests,
  public.srt_tank_sessions,
  public.srt_mobile_tank_calibration,
  public.srt_mobile_tanks,
  public.sgpa_events,
  public.sgpa_assets,
  public.sgpa_causes,
  public.smt_maintenance_logs,
  public.smt_preventive_plans,
  public.smt_equipment,
  public.sbp_assets,
  public.tank_operations,
  public.daily_production_reports,
  public.production_data,
  public.calibration_data,
  public.seal_data,
  public.fcv_data,
  public.fcv_calculation_logs,
  public.transfer_destination_categories,
  public.tanks,
  public.wells,
  public.production_fields,
  public.teams,
  public.projects,
  public.app_settings
RESTART IDENTITY CASCADE;
