ALTER TABLE srt_well_tests
ADD COLUMN IF NOT EXISTS fe NUMERIC DEFAULT 1,
ADD COLUMN IF NOT EXISTS fcv NUMERIC DEFAULT 1,
ADD COLUMN IF NOT EXISTS fdt NUMERIC DEFAULT 1,
ADD COLUMN IF NOT EXISTS v_oil_corrected NUMERIC DEFAULT 0;
